export default {
  frame: {
    sysInform: '系统消息',
    loadingMore: '加载更多...',
    doc: '详细文档',
    warning: '服务器繁忙，请稍后再试 ...',
    top: '置顶',
    expiryDate: '有效周期',
    to: '至',
    relatedFiles: '相关附件',
    home: '首页',
    list: '消息列表',
    title: '消息列表',
    listDetail: '消息详情',
    systemInfo: '系统消息',
    systemInfoContent: '您的token已失效，请尝试重新登录！',
    pagerFooter: '中国移动国际有限公司 版权所有',
    changeTitle: '修改密码',
    accountId: '用户ID',
    oldPsd: '旧密码',
    newPsd: '新密码',
    confirmNew: '确认新密码',
    mobileNum: '手机号码',
    psdRule: '密码规则',
    rule1: 'The length of new password must be more than five',
    rule2: 'Password can include three of the follow three types:',
    rule3: 'Upper case letters from A to Z',
    rule4: 'case letters from A to Z',
    rule5: 'numbers from 0 to 9',
    rule6: 'password is effectively in 90 days',
    submit: '提交'
  }
}
