export default {
  frame: {
    sysInform: '系统消息',
    loadingMore: '加载更多...',
    doc: '详细文档',
    warning: '服务器繁忙，请稍后再试 ...',
    top: '置顶',
    expiryDate: '有效周期',
    to: '至',
    relatedFiles: '相关附件',
    home: '首页',
    list: '消息列表',
    title: '消息列表',
    listDetail: '消息详情',
    systemInfo: '系统消息',
    systemInfoContent: '您的token已失效，请尝试重新登录！',
    pagerFooter: '中国移动国际有限公司 版权所有',
    changeTitle: '修改密码',
    accountId: '用户ID',
    oldPsd: '旧密码',
    newPsd: '新密码',
    confirmNew: '确认新密码',
    mobileNum: '手机号码',
    psdRule: '密码规则',
    rule1: '8位或以上长度',
    rule2: '包含来自以下三类:',
    rule3: '大写英文字母（从 A 到 Z）',
    rule4: '小写英文字母（从 a 到 z）',
    rule5: '10 个基本数字（从 0 到 9）',
    rule6: '密码有效时间为90天',
    submit: '提交',
    check: '新密码与确认密码不一致',
    inputNull: '输入框不能为空',
    btn_yes: '确定',
    change_psd: '修改密码'
  }
}
